blog:
    resource: "@BlogBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

authentication:
    resource: "@BlogBundle/Controller/LoginController.php"
    type:     annotation
    prefix:   /


logout:
    path:   /logout

