security:
    encoders:
        Cvut\Fit\BiPwt\BlogBundle\Entity\User: plaintext

    providers:
        db_provider:
            entity:
                class: BlogBundle:User
                property: name
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /

        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
#       secured_area:

    access_control:
        - { path: ^/((postNew)|(postEdit)|(postRemove)), roles: ROLE_AUTHOR }
        - { path: ^/postDetails/\d+/(edit|remove), roles: ROLE_AUTHOR }
        - { path: ^/postDetails/\d+/answer, roles: ROLE_READER}

    role_hierarchy:
         ROLE_AUTHOR: ROLE_USER
         ROLE_READER: ROLE_USER
         ROLE_ADMIN:  ROLE_USER, ROLE_AUTHOR, ROLE_READER

